class apiv0:
    root = "/apiv0/"
    authored_month_count = "/apiv0/authored_month_count"
    count = "/apiv0/count"
    full_view = "/apiv0/full/"
    ivorn = "/apiv0/ivorn"
    ivorn_cited_count = "/apiv0/ivorn_cited_count"
    ivorn_ref_count = "/apiv0/ivorn_ref_count"
    role_count = "/apiv0/role_count"
    stream_count = "/apiv0/stream_count"
    stream_role_count = "/apiv0/stream_role_count"
    xml_view = "/apiv0/xml/"
